### ISSUE TITLE
The pretrained backbone checkpoints from UCN are unavailable now.

### ISSUE THREAD

**Issue by felixpun** [YoungSean/UnseenObjectsWithMeanShift#1]
The url of https://drive.google.com/file/d/1O-ymMGD_qDEtYxRU19zSv17Lgg6fSinQ/view?usp=sharing is invalid.

**Comment by ryuichi-maeda** [comment]
Hi @felixpun 
I encountered the same issue with the link provided.
Have you been able to locate the correct file or an alternative source for it?

**Comment by YoungSean** [comment]
The new Box link in their repo:  [checkpoints](https://utdallas.app.box.com/s/9vt68miar920hf36egeybfflzvt8c676)

**Comment by ryuichi-maeda** [comment]
Thanks for the update! I was able to download the checkpoints from the provided link.
