### ISSUE TITLE
can't download the ocid and osd

### ISSUE THREAD

**Issue by alaladingding** [YoungSean/UnseenObjectsWithMeanShift#2]
I can't dowdload The Object Clutter Indoor Dataset (OCID) and Object Segmentation Dataset (OSD) from (https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/object-clutter-indoor-dataset/), do someone have the resource? I would greatly appreciate your assistance in obtaining it.

**Comment by rcao-hk** [comment]
Same issue.

**Comment by YoungSean** [comment]
There is an [OCID](https://researchdata.tuwien.at/records/pcbjd-4wa12) download link on their [webpage](https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/object-clutter-indoor-dataset/).
![image](https://github.com/YoungSean/UnseenObjectsWithMeanShift/assets/19357554/92774b8e-e833-4484-95a5-8e76e369cf34)

**Comment by YoungSean** [comment]
We provide the backup links for OSD: [OSD-0.2.zip](https://utdallas.box.com/shared/static/latrbafzsofe36brxq9l8xaa2yrwkvkw.zip) and [OSD-0.2-depth.zip](https://utdallas.box.com/s/ncnjr4ltajku5wu7r3yhjwmp9mx9ne76). Please to adhere to the licensing agreements of the [official OSD](https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/osd/) dataset. 

After unzipping two files, you may copy files from OSD-0.2 folder to OSD-0.2-depth folder.
