### ISSUE TITLE
Extract individual Object Masks

### ISSUE THREAD

**Issue by AmanSriv97** [YoungSean/UnseenObjectsWithMeanShift#4]
Hi. I am trying to use your work in my project in which i want the segmented masks of the objects kept on the table. Upon running test_image_with_ms_transformer.py code i am able to visualize a single image with multiple masks on it. But I need multiple masks such that each mask has just one object. 
Do you guys have such code anywhere in the repo where i can utilize it. OR how to get this required result.?

**Comment by YoungSean** [comment]
hi, in this function [test_sample_crop_nolabel](https://github.com/YoungSean/UnseenObjectsWithMeanShift/blob/master/lib/fcn/test_utils.py#L339), there are out_label and binary_mask variables. I guess those may be what you need. Generally, the model would output **instances** that you can check out.
